### ISSUE TITLE
在2023.2.1版本下引入插件会报错。重启IDEA后Configuration里没有Resin服务。

### ISSUE THREAD

**Issue by dragoncoder7** [chao2hang/resin_idea#1]
您好 我使用的IDEA版本是IntelliJ IDEA 2023.2.1 (Ultimate Edition) Build #IU-232.9559.62 开发环境为Windows10 
我引入了这两个javaee-appServers-resin.zip 和 Source code(zip)
第一次引入javaee-appServers-resin.zip后产生报错

![d7b827d101220d91c8df9337b22c7db](https://github.com/user-attachments/assets/da2e83e7-2e6c-4565-b074-8c60f56370b7)

好像应该不影响 从内容上来看是插件的描述无效。
重启后插件里能看到Resin 
![image](https://github.com/user-attachments/assets/afc75023-ef1a-4b5f-9720-ac1555da86aa)

打钩选择启用 然后重新启动IDEA 但是Configuration里没有Resin服务。
如图所示
![image](https://github.com/user-attachments/assets/b7b7e568-be38-4930-bd8a-5762afb93344)

**Comment by dragoncoder7** [comment]
然后又单独引入了[resin_idea-1.0.zip] 重新启动后还是无法正常使用resin。
以及两者都引入 configuration里也没有resin。

**Comment by chao2hang** [comment]
实际我在最新2024.3.1 版本的Linux （243.22562.145 ）和Windows （忘记版本号了）测试过是可用的。

稍等，我安装一个老版本的测试研究一下~

**Comment by dragoncoder7** [comment]
> 实际我在最新2024.3.1 版本的Linux （243.22562.145 ）和Windows （忘记版本号了）测试过是可用的。
> 
> 稍等，我安装一个老版本的测试研究一下~

好的 感谢大佬！

**Comment by chao2hang** [comment]
没有找到2023.2.1 我安装了 2023.2.8 (231.10335.12)，测试确实存在上述问题。

建议先安装最新的2024.3.1使用这个插件 或 安装 2023.1.7使用官方插件，可以使用Toolbox 快速安装。

![image](https://github.com/user-attachments/assets/5a32361a-283d-437c-8d8d-6236746d7e71)

如果需要激活建议参考nopj.cn中关于[jetbrains](https://nopj.cn/article/93595d19-1b85-4f27-a1c4-5da66be8909f)相关的文章。

**Comment by dragoncoder7** [comment]
好的 感谢大佬抽空援助~ 成功使用上resin了 ^_^
